import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { CartProvider } from "@/components/context/cart";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(cookies().get("token")?.value, "json");
  // let json = {};
  // try {

  //   const cookie = cookies().get("token")?.value

  //   const response = await fetch("http://localhost:3000/api/whoami", {
  //     method: "POST",
  //     headers: {
  //       "Cookie": `token=${cookie}`,
  //     },
  //   });

  //   console.log(response)
  //   // json = await response.json();
  // } catch (error) {}

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <UserProvider value={{ user: json }}> */}
          <CartProvider>
            <Header />
            <main className="container mx-auto p-8"> {children}</main>
            <Footer />
          </CartProvider>
        {/* </UserProvider> */}
      </body>
    </html>
  );
}
